name: Manul update from github


on: 

  workflow_dispatch:
      inputs:
        name:

          description: Person to greet
          default: world
          required: true


  job:
    greet:

      runs-on: ubuntu:latest
      
      steps:

        - name: Send greeting
          run: echo "Hello ${{ githib.event.input.name }}"
        
